added lastmod to sponsorship
nwplus/database-schemas pull request #3
Opened 2020-07-30 22:46 UTC by yungalyx

2020-07-30 23:11 UTC, rmehri01 reviewed
Now that I think of it, shouldn't sponsors have a rank too?

2020-07-30 23:31 UTC, yungalyx commented
@rmehri01 you're right, ill ask spons + design

2020-08-05 02:27 UTC, Ciuffi requested changes
Sorry for the nitpicky comments, this just makes the documentation easier to understand.

2020-08-05 02:27 UTC, Ciuffi commented on nw-firestore-schema.ts
> +  teir: "platinum"
Typo in teir, also could you make this a type, so its easier to understand what the options are?

aka
```typescript
type Tier = "gold" | "silver" | "platinum"
````

and then in the sponsors interface:

```typescript
interface Sponsor {
tier: Tier = "gold";
}
```

2020-08-05 02:27 UTC, Ciuffi commented on nw-firestore-schema.ts
> +
Should remove the extra empty space, leads to ugly code.

2020-09-11 09:00 UTC, Ciuffi approved these changes
fixed

2020-09-11 09:00 UTC, merged